//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public int PublisherID { get; set; }
        public string PubYear { get; set; }
        public string ISBN { get; set; }
        public double Price { get; set; }
        public int BookPropertyID { get; set; }
        public int BookTypeID { get; set; }
        public string LastTime { get; set; }
        public string DisabledTime { get; set; }
        public int Status { get; set; }
    }
}
