//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartJobTeachers
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool Sex { get; set; }
        public Nullable<int> EduID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public System.DateTime InTime { get; set; }
        public string Tel { get; set; }
        public string UnitName { get; set; }
        public string ContactName { get; set; }
        public string JudgeText { get; set; }
        public System.DateTime LastTime { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
